version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    hostname: minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_HTTP_TRACE: /dev/stdout
    command: server /data
  adminio-ui:
    image: rzrbld/adminio-ui:latest
    ports:
      - "80:80"
  adminio-api:
    image: rzrbld/adminio-api:latest
    environment:
      MINIO_ACCESS: minio
      MINIO_SECRET: minio123
      MINIO_HOST_PORT: minio:9000
    depends_on:
      - minio
      - adminio-ui
    ports:
      - "8080:8080"