# https://taskfile.dev

version: '3'

vars:
  PLUGIN_VERSION: 1.2.0
  OUTPUT_FILENAME: terraform-provider-minio_{{.PLUGIN_VERSION}}

tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the plugin into current folder.
    cmds:
      - echo "Building {{.OUTPUT_FILENAME}}"
      - go build -o {{.OUTPUT_FILENAME}}
      - echo "Done!"
    silent: true

  install:
    desc: Build and install the plugin in the correct folder (resolved automatically based on current Operating System).
    vars: 
      WINDOWS_FOLDER: '%APPDATA%\HashiCorp\Terraform\plugins\registry.terraform.io\aminueza\minio\{{.PLUGIN_VERSION}}\{{OS}}_{{ARCH}}'
      DARWIN_FOLDER: '~/Library/Application\ Support/io.terraform/plugins/registry.terraform.io/aminueza/minio/{{.PLUGIN_VERSION}}/{{OS}}_{{ARCH}}'
      UNIX_FOLDER: '~/.local/share/terraform/plugins/registry.terraform.io/aminueza/minio/{{.PLUGIN_VERSION}}/{{OS}}_{{ARCH}}'
    cmds:
      - |
        {{if eq OS "windows"}}
          echo "Building and installing plugin in {{.WINDOWS_FOLDER}}/{{.OUTPUT_FILENAME}}"
          go build -o {{.WINDOWS_FOLDER}}/{{.OUTPUT_FILENAME}}
        {{else}}
          {{if eq OS "darwin"}}
            echo "Building and installing plugin in {{.DARWIN_FOLDER}}/{{.OUTPUT_FILENAME}}"
            go build -o {{.DARWIN_FOLDER}}/{{.OUTPUT_FILENAME}}
          {{else}}
            echo "Building and installing plugin in {{.UNIX_FOLDER}}/{{.OUTPUT_FILENAME}}"
            go build -o {{.UNIX_FOLDER}}/{{.OUTPUT_FILENAME}}
          {{end}}
        {{end}}
      - echo "Done!"
    silent: true

  test:
    desc: Run the package tests.
    env: 
      TF_ACC: 0
      MINIO_ENDPOINT: localhost:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ENABLE_HTTPS: false
    cmds:
      - go test -v -cover ./minio
    silent: true
