name: Terraform Provider CI
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.go'
      - '**.tf'
      - 'go.*'
      - '.github/workflows/*.yml'
jobs:
  checkup:
    name: Checkup
    runs-on: ubuntu-latest
    env:
      GOARCH: amd64
      GOOS: linux
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Run fmt
        uses: aminueza/go-github-action/fmt@master
      - name: Run sec
        uses: aminueza/go-github-action/sec@master
        with:
          path: minio/...
      - name: Run vet
        uses: aminueza/go-github-action/vet@master
      - name: Run errcheck
        uses: aminueza/go-github-action/errcheck@master
        with:
          path: minio/...
      - name: Run linter
        uses: aminueza/go-github-action/lint@master
      - name: Set up Go 
        uses: actions/setup-go@v1
        with:
          go-version: ${{ secrets.GO_VERSION }}
        id: go
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: go test ./...
      - name: Build
        run: make build
